# Generated by Django 4.2.5 on 2023-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_alter_chat_users_alter_chatuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_secret',
            field=models.IntegerField(default=483848),
            preserve_default=False,
        ),
    ]
