# Generated by Django 4.2.5 on 2023-09-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_chat_users_alter_chatuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/chat/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/profile/'),
        ),
    ]
