# Generated by Django 4.2.5 on 2023-09-16 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_chat_chat_pic_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recepient',
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
