# Generated by Django 4.2.5 on 2023-09-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='chat',
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chat', to='users.chatuser'),
        ),
    ]
