# Generated by Django 4.2.5 on 2023-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_message_likes_message_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('editor', 'editor'), (None, None)], max_length=10, null=True),
        ),
    ]
