# Generated by Django 4.2.5 on 2023-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_chat_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='chats',
            field=models.ManyToManyField(null=True, related_name='folder', to='users.chat'),
        ),
    ]
